- id: a
  alias: Christmas Lights On
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:10:00"
    - platform: time
      at: '05:45:00'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.ge_45604_outdoor_module_switch
    - service: switch.turn_on
      data:
        entity_id: switch.zooz_zen06_switch
    - service: notify.pushover
      data:
        message: "XMAS lights have been turned on"
        title: "Lights on"
- id: b
  alias: Christmas Lights Off
  trigger:
    - platform: time
      at: '01:00:00'
    - platform: sun
      event: sunrise
      offset: "-00:10:00"
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.zooz_zen06_switch 
    - service: switch.turn_off
      data:
        entity_id: switch.ge_45604_outdoor_module_switch
    - service: notify.pushover
      data:
        message: "XMAS lights have been turned off"
        title: "Lights off"
- id: c
  alias: Laundry room lights on
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_motion_detector_sensor_laundry
    to: 'on'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.laundry_room_lights
- id: d
  alias: Laundry room lights off
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_motion_detector_sensor_laundry
    to: 'off'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.laundry_room_lights
- id: e
  alias: Mechanical room lights on
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_motion_detector_sensor_mechanical
    to: 'on'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.mechanical_room_lights
- id: f
  alias: Mechanical room lights off
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_motion_detector_sensor_mechanical
    to: 'off'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.mechanical_room_lights
- id: g
  alias: Activate Launch Sequence
  trigger:
    - platform: time
      at: '06:35:00'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - thu
      - fri
  action:
    - service: script.turn_on
      entity_id: script.launch_sequence
- id: h
  alias: Activate Launch Sequence - LATE START
  trigger:
    - platform: time
      at: '07:15:00'
  condition:
    condition: time
    weekday:
      - wed
  action:
    - service: script.turn_on
      entity_id: script.launch_sequence
