- id: a
  alias: Christmas Lights On
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:10:00"
    - platform: time
      at: '05:45:00'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.ge_45604_outdoor_module_switch
    - service: switch.turn_on
      data:
        entity_id: switch.zooz_zen06_switch
- id: b
  alias: Christmas Lights Off
  trigger:
    - platform: time
      at: '01:00:00'
    - platform: sun
      event: sunrise
      offset: "-00:10:00"
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.zooz_zen06_switch 
    - service: switch.turn_off
      data:
        entity_id: switch.ge_45604_outdoor_module_switch
- id: c
  alias: Laundry room lights on
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_motion_detector_sensor_laundry
    to: 'on'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.laundry_room_lights
- id: d
  alias: Laundry room lights off
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_motion_detector_sensor_laundry
    to: 'off'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.laundry_room_lights
- id: e
  alias: Mechanical room lights on
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_motion_detector_sensor_mechanical
    to: 'on'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.mechanical_room_lights
- id: f
  alias: Mechanical room lights off
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_motion_detector_sensor_mechanical
    to: 'off'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.mechanical_room_lights
- id: g
  alias: Activate Launch Sequence
  trigger:
    - platform: time
      at: '06:45:00'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - thu
      - fri
  action:
    - service: script.turn_on
      entity_id: script.launch_sequence
- id: h
  alias: Activate Launch Sequence - LATE START
  trigger:
    - platform: time
      at: '07:25:00'
  condition:
    condition: time
    weekday:
      - wed
  action:
    - service: script.turn_on
      entity_id: script.launch_sequence
- id: i
  alias: Jank Alarm System
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_kitchen
      to: 'on'
    - platform: state
      entity_id: binary_sensor.ecolink_motion_detector_sensor_mechanical
      to: 'on'
    - platform: state
      entity_id: binary_sensor.ecolink_motion_detector_sensor_laundry
      to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.alarm_system_armed
    state: 'on'
  action:
    - service: notify.pushover
      data:
        message: "Alarm tripped"
        title: "A motion sensor has been tripped."
    - service: media_player.volume_set
      data:
        entity_id:
          - media_player.kitchen
        volume_level: 1.0
    - service: tts.google_translate_say
      entity_id:
        - media_player.kitchen
      data:
        message: "Attention! Intruder detected! Police have been notified. Repeat, police have been notified."
    - service: media_player.volume_set
      data:
        entity_id:
          - media_player.kitchen
        volume_level: 1.0
    - service: tts.google_translate_say
      entity_id:
        - media_player.kitchen
      data:
        message: "Attention! Intruder detected! Police have been notified. Repeat, police have been notified."
- id: j
  alias: Notify when external IP address changes
  initial_state: on
  trigger: 
    platform: state
    entity_id: sensor.dnsip
  action:
    - service: notify.pushover
      data:
        title: "Public IP address changed"
        message: "New external IP address is {{ states('sensor.myip') }}"
