homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 243
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

zeroconf:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Sensors
sensor:
  # IP Address
  - platform: dnsip
  # Weather prediction
  - platform: yr
  # Battery Levels
  - platform: template
    sensors:
      laundry_room_sensor_battery:
        friendly_name: 'Batt Level Laundry'
        value_template: >-
          {%- if states.zwave.ecolink_motion_detector -%}
            {{ states.zwave.ecolink_motion_detector.attributes.battery_level }}
          {%- else -%}
            n/a
          {%- endif -%}
        entity_id: zwave.ecolink_motion_detector
        unit_of_measurement: '%'
      mechanical_room_sensor_battery:
        friendly_name: 'Batt Level Mechanical Room'
        value_template: >-
          {%- if states.zwave.ecolink_motion_detector -%}
            {{ states.zwave.ecolink_motion_detector.attributes.battery_level }}
          {%- else -%}
            n/a
          {%- endif -%}
        entity_id: zwave.ecolink_motion_detector_2
        unit_of_measurement: '%'
      zooz_multisensor_battery:
        value_template: "{{ states.zwave.zooz_zse40_4in1_sensor_2.attributes.battery_level }}"
        friendly_name: "Batt Zooz Multi Sensor"
        entity_id: zwave.zooz_zse40_4in1_sensor_2
        unit_of_measurement: '%'
binary_sensor:
  - platform: template
    sensors:
      motion_sensor_kitchen:
        friendly_name: "Motion Sensor Kitchen"
        value_template: "{{ states.sensor.zooz_zse40_4in1_sensor_alarm_level.state|int >= 254 }}"
  - platform: template
    sensors:
      motion_sensor_basement_hall:
        friendly_name: "Motion Sensor Basement Hall"
        value_template: "{{ states.sensor.ge_26933_smart_motion_dimmer_burglar_3.state|int == 8 }}"
  - platform: template
    sensors:
      upstairs_heating:
        friendly_name: "Upstairs heating"
        value_template: "{{ states.climate.upstairs.attributes.operation == 'heat' }}"
  - platform: template
    sensors:
      main_floor_heating:
        friendly_name: "Main Floor heating"
        value_template: "{{ states.climate.main_floor.attributes.operation == 'heat' }}"
  - platform: template
    sensors:
      basement_heating:
        friendly_name: "Basement heating"
        value_template: "{{ states.climate.basement.attributes.operation == 'heat' }}"

# Input booleans
input_boolean:
  alarm_system_armed:
    name: Alarm System Armed
    initial: off

# Text to speech
tts:
  - platform: google_translate

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://hassio.local:3218

# MQTT / Owntracks stuff
mqtt:
  broker: m15.cloudmqtt.com
  port: 16729
  username: !secret cloudmqtt_username
  password: !secret cloudmqtt_password

owntracks:
  max_gps_accuracy: 200
  waypoints: false
  mqtt_topic: "owntracks/#"
  events_only: false

zone:
  # This will override the default home zone
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 250
    icon: mdi:account-multiple
  - name: SPA Randolph
    latitude: 44.925965
    longitude: -93.173472
    radius: 250
    icon: mdi:school

notify:
  - name: pushover
    platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key
zwave:
  usb_path: /dev/ttyACM0
  polling_interval: 3000
  network_key: !secret zwave_network_key
wake_on_lan:
  #Needed for WebOS TV
media_player:
  - platform: webostv
    host: 192.168.1.33
    name: Family Room TV
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: "C8-08-E9-DA-00-6E"
ecobee:
  api_key: !secret ecobee_api_key
