homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 243
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Sensors
sensor:
  # Weather prediction
  - platform: yr
  - platform: template
    sensors:
      laundry_sensor_battery:
        friendly_name: 'Batt Level Laundry'
        value_template: >-
          {%- if states.zwave.ecolink_motion_detector -%}
            {{ states.zwave.ecolink_motion_detector.attributes.battery_level }}
          {%- else -%}
            n/a
          {%- endif -%}
        unit_of_measurement: '%'
        entity_id: zwave.ecolink_motion_detector

binary_sensor:
  - platform: template
    sensors:
      bmw_needs_charge:
        friendly_name: "BMW Needs Charge"
        value_template: "{{ states.sensor.i3_94__rex_charging_level_hv.state|int < 30 and is_state('binary_sensor.i3_94__rex_charging_status','off') and is_state('device_tracker.i3_94__rex','home') }}"

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

# Example configuration.yaml entry
bmw_connected_drive:
  name:
    username: !secret bmw_username
    password: !secret bmw_password
    region: north_america
    
panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://hassio.local:3218

# MQTT / Owntracks stuff
mqtt:
  broker: m15.cloudmqtt.com
  port: 16729
  username: !secret cloudmqtt_username
  password: !secret cloudmqtt_password

device_tracker:
  - platform: bmw_connected_drive
    #consider_home: 300
    interval_seconds: 120

owntracks:
  max_gps_accuracy: 200
  waypoints: false
  mqtt_topic: "owntracks/#"
  events_only: false

zone:
  # This will override the default home zone
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 250
    icon: mdi:account-multiple
  - name: SPA Randolph
    latitude: 44.925965
    longitude: -93.173472
    radius: 250
    icon: mdi:school

notify:
  - name: pushover
    platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key
zwave:
  usb_path: /dev/ttyACM0
  polling_interval: 3000
  network_key: !secret zwave_network_key
wake_on_lan:
  #Needed for WebOS TV
media_player:
  - platform: webostv
    host: 192.168.1.33
    name: Family Room TV
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: "C8-08-E9-DA-00-6E"
alert:
  charge_car:
    name: Charge car, battery is {{ states.sensor.i3_94__rex_charging_level_hv.state }}%
    done_message: Car doesn't need charge -- alert over
    entity_id: binary_sensor.bmw_needs_charge
    state: 'on'
    can_acknowledge: false
    repeat:
      - 60
      - 1440
    notifiers:
      - pushover
ecobee:
  api_key: !secret ecobee_api_key
